### ISSUE TITLE
Missing footprint for new RP2350 Stamp XL?

### ISSUE THREAD

**Issue by JamesDunne** [solderparty/rp2xxx_stamp_footprints#1]
Came across https://www.solder.party/docs/rp2350-stamp-xl/ and it links to this repo but I don't see any footprints for the newer RP2350 Stamp XL, only the older RP2040s.

**Comment by arturo182** [comment]
Yes, I will add it in the coming days, the new RP2350 Stamps were just announced yesterday 🙂

**Comment by arturo182** [comment]
The XL symbols and footprints have now been added for KiCad, Eagle, and EasyEDA :)

Also .step 3D models in the KiCad folder.
